version: 2.1

orbs:
  makepress-orb: makepress/makepress-orb@2.4.1

workflows:
  version: 2
  build:
    jobs:
      - makepress-orb/publish-docker:
          context: [yuiyukihira]
          username: GITHUB_USERNAME
          password: GITHUB_PAT
          image: yuiyukihira/rust
          registry: ghcr.io
          tag: latest
          dockerfile: rust
