version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  version: 2
  build:
    jobs:
      - rust:
          context: [aws]

jobs:
  rust:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          path: rust
          repo: makepress-rust
          create-repo: true
